<?php
/**
 * Created by PhpStorm.
 * User: julien
 * Date: 06.06.19
 * Time: 19:07
 */


/**
 * Implements hook_theme().
 */
function delphi_theme($existing, $type, $theme, $path)
{
    return array(
        'delphi_boxplot' => array(
            'variables' => array(
                'avg_percent' => NULL,
                'avg_absolut' => NULL,
                'median_absolut' => NULL,
                'median_percent' => NULL,
                'first_quantil_percent' => NULL,
                'first_quantil_absolut' => NULL,
                'third_quantil_percent' => NULL,
                'third_quantil_absolut' => NULL,
                'third_quantil2' => NULL,

            ),
        ),
    );
}